### PR TITLE
Update Batcher_Node.gd

### PR DESCRIPTION
**Pull request by Yogoda**
- Fixes errors when meshinstance has not staticbody
- Add support for scenes
- Add support for material override
- Fixes duplicated code

### CODE REVIEW

**Comment by Yogoda** [comment]
Hello, I love your plugin, exactly what I need, but there are some issues with it.

I committed fixes, can you check?

**Comment by OrigamiDev-Pete** [comment]
Hi, I just tried out your  code and it seems to work well. Thanks for fixing up some of those problems that I had overlooked. The material override and scenes are great additions.

**Comment by Yogoda** [comment]
Awesome, thank you :)

oops, I forgot to restore the material when unbatching:

				#restore material
				if mmi.material_override:
					mesh.material_override = mmi.material_override

can you add it? (but only when it is not a scene)

Thanks!

**Comment by OrigamiDev-Pete** [comment]
No problem. I'll have a look at that tomorrow.

**Pull request merged**
